#파일 규격버전
version: '3.3'
#컨테이너 정의
services:
  #서비스 명
  mongodb:
    #사용할 이미지
    image: mongo
    #컨테이너 실행 시 재시작
    restart: always
    #컨테이너명
    container_name: mongodb-container
    #접근 포트 설정
    ports:
      - '27017:27017'
    # -e 옵션
    environment:
      #mongodb 계정 및 패스워드 설정 옵션
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      # -v
      - data:/data/db
volumes:
  data:
    external: false
